/**
 * 
 */
package org.openntf.red.core.thread;

/**
 * Exception generated by the Thread Manager.
 * 
 * @author Vladimir Kornienko
 * @see ThreadManager
 * @since 0.4.0
 */
public class ThreadManagerException extends RuntimeException {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * Default constructor.
	 * 
	 * @since 0.4.0
	 */
	public ThreadManagerException() {
		// TODO Auto-generated constructor stub
	}

	/**
	 * Default constructor with message text.
	 * 
	 * @param msg
	 *            Message text
	 * @since 0.4.0
	 */
	public ThreadManagerException(String msg) {
		super(msg);
		// TODO Auto-generated constructor stub
	}

	/**
	 * Default constructor with cause of error.
	 * 
	 * @param e
	 *            Cause of error
	 * @since 0.4.0
	 */
	public ThreadManagerException(Throwable e) {
		super(e);
		// TODO Auto-generated constructor stub
	}

	/**
	 * Default constructor with message text and cause of error.
	 * 
	 * @param msg
	 *            Message text
	 * @param e
	 *            Cuase of error
	 * @since 0.4.0
	 */
	public ThreadManagerException(String msg, Throwable e) {
		super(msg, e);
		// TODO Auto-generated constructor stub
	}

	/**
	 * Default constructor with message text, cause of error, and flags:
	 * suppression enabled and writable stack trace enabled.
	 * 
	 * @param msg
	 *            Message text
	 * @param e
	 *            Cause of error
	 * @param suppression
	 *            Flag - suppression enabled
	 * @param writest
	 *            Flag - writable stack trace enabled
	 * @since 0.4.0
	 */
	public ThreadManagerException(String msg, Throwable e, boolean suppression, boolean writest) {
		super(msg, e, suppression, writest);
		// TODO Auto-generated constructor stub
	}

}
